cojar/jigumiyak

- src/main/java/com/ll/jigumiyak/board/Board.java
- src/main/java/com/ll/jigumiyak/board/BoardController.java
- src/main/java/com/ll/jigumiyak/board/BoardService.java
- src/main/java/com/ll/jigumiyak/board_comment/BoardComment.java
- src/main/java/com/ll/jigumiyak/board_comment/BoardCommentController.java
- src/main/java/com/ll/jigumiyak/board_comment/BoardCommentService.java
- src/main/resources/templates/bcomment_form.html
- src/main/resources/templates/board_detail.html
- src/main/resources/templates/footer.html
- src/main/resources/templates/navbar.html
**RQ-0105**
게시글 상세 - 해당 게시글의 작성자일 경우 수정 / 삭제 버튼이 표시되고 해당 기능을 이용할 수 있다.						
**RQ-0106**
게시글 상세 - 게시글 당 1번의 추천을 할 수 있다.						
**RQ-0107**
게시글 상세 - 로그인한 사용자가 추천 버튼 클릭 시 확인 알림이 표시되고 확인 버튼 클릭 시 추천 버튼의 색상이 변경되고 추천 수가 증가한다.	_(추천 수만)_					
**RQ-0109**
게시글 상세 - 목록 버튼을 누르면 자유게시판 목록 페이지로 이동한다.						
**RQ-0112**
게시글 상세 - 상단에 게시물에 작성된 총 댓글 개수가 표시된다.						
**RQ-0114**
게시글 상세 - 댓글 작성자 / 내용 / 작성일시 / 수정일시 / 추천이 표시된다.						
**RQ-0118**
게시글 상세 - 댓글 작성자에게는 해당 댓글의 수정/삭제 버튼이 표시되고 기능을 이용할 수 있다.											
- 댓글 등록 폼으로 일단 연결해두었고 나중에 수정 예정
> 자유게시판 RQ-0105 외

- src/main/java/com/ll/jigumiyak/security/DefaultFailureHandler.java
- src/main/java/com/ll/jigumiyak/security/DefaultSuccessHandler.java
- src/main/java/com/ll/jigumiyak/user/UserController.java
- src/main/java/com/ll/jigumiyak/user/UserSecurityService.java
- src/main/resources/static/login.css
- src/main/resources/templates/login.html
- src/main/resources/templates/signup.html
**RQ-0024**
아이디와 비밀번호 모두 입력되었을 때 로그인 버튼이 활성화된다.
**RQ-0026**
로그인 버튼 클릭 시 아이디와 비밀번호를 조회하여 아이디가 존재하지 않을 경우 “가입된 통합회원 계정이 아닙니다.” 라는 알림이 표시된다.
**RQ-0027**
로그인 버튼 클릭 시 아이디와 비밀번호를 조회하여 아이디는 존재하지만 비밀번호가 일치하지 않을 경우 “비밀번호가 일치하지 않습니다.” 라는 알림이 표시된다.
**RQ-0033**
로그인 페이지 우측 상단에 닫기 버튼이 있고, 닫기 버튼 클릭 시 메인페이지로 이동한다.
(내역 수정 필요)  로그인 페이지 하단에 메인화면 버튼이 있고, 버튼 클릭 시 메인페이지로 이동한다.
**RQ-0034**
로그인 페이지 하단에 회원가입, 아이디 찾기, 비밀번호 찾기 버튼이 있다.
**RQ-0035**
회원가입 버튼을 클릭하면 회원가입 페이지로 이동한다.
**RQ-0045**
영문+숫자 8자 이상의 비밀번호를 입력할 수 있다.
**RQ-0051**
페이지 하단에 회원가입, 로그인, 메인으로 버튼이 표시된다.
- 일반 로그인 파트 요구사항 완료
- 기완료된 요구사항 체크해서 기재
확인 후 리뷰 부탁드립니다.
> 로그인, 회원가입 - RQ-0024 외

- src/main/resources/static/common.js
- src/main/resources/static/login.js
- src/main/resources/static/signup.js
- src/main/resources/templates/layout.html
- src/main/resources/templates/login.html
- src/main/resources/templates/navbar.html
- src/main/resources/templates/signup.html
**RQ-0001**
 로그인하지 않은 사용자가 로그인이 필요한 페이지로 이동하는 버튼 클릭 시 “로그인이 필요한 서비스입니다. 확인을 누르시면 로그인 페이지로 이동합니다.” 라는 confirm 알림이 표시된다.
**RQ-0002**
 confirm 알림 창에서 확인 버튼 클릭 시 로그인 페이지로 이동하고, 로그인이 정상적으로 완료되면 이동하려던 페이지로 이동한다.
- 로그인이 필요한 컨트롤러에 요청 보낼 때 처리하는 로직 작성
- 예시 코드
`<a class="cursor-pointer" th:attr="onclick=|_anonymous('user/mypage', '${#authentication.details.sessionId != null}')|"></a>`
- 해당 기능 이용 시 아래 코드 템플릿에 삽입 필수
`<script type="text/javascript" th:inline="javascript" th:src="@{/common.js}"></script>`
확인 후 리뷰 부탁드립니다.
> 공통 - RQ-0001, 0002

- src/main/java/com/ll/jigumiyak/board_comment/BoardCommentController.java
- src/main/resources/templates/footer.html
> 자유게시판 댓글 버그 수정

- Dockerfile
> 빌드 - RQ-0000

- src/main/java/com/ll/jigumiyak/user/UserController.java
- src/main/resources/templates/board_detail.html
- src/main/resources/templates/board_form.html
- src/main/resources/templates/board_list.html
- src/main/resources/templates/mypage.html
- src/main/resources/templates/navbar.html
> 게시판 글 상세/ 마이페이지 프론트

- src/main/java/com/ll/jigumiyak/inquiry/InquiryController.java
- src/main/java/com/ll/jigumiyak/user/UserController.java
- src/main/resources/templates/findIDandPW.html
- src/main/resources/templates/inquiry_list.html
- src/main/resources/templates/inquiry_main.html
- src/main/resources/templates/navbar.html
**문의하기 목록 페이지 프론트 제작
문의하기 카테고리별 페이지 기본 레이아웃 제작** 
- 카테고리별 페이지는 추후 추가 예정
- 카테고리별로 코드 복사한 후 수정하면 됨
> Feature fr

- src/main/java/com/ll/jigumiyak/board/Board.java
- src/main/java/com/ll/jigumiyak/board/BoardController.java
- src/main/java/com/ll/jigumiyak/board/BoardService.java
- src/main/resources/templates/board_list.html
**RQ-0095**
- 페이지 당 표시될 게시글 개수를 선택할 수 있다
**RQ-0096**
- 모든 사용자가 정렬 기능과 검색 기능을 이용할 수 있다.	
**RQ-0097**
- 정렬 옵션으로 조회순, 추천순, 오래된순이 있으며, 해당 버튼 클릭 시 정렬 옵션에 맞는 목록이 표시된다.
CL-16 게시판 목록 전체 완료했습니다.
> 게시판 목록 RQ-0095 외

- src/main/java/com/ll/jigumiyak/user/UserController.java
- src/main/java/com/ll/jigumiyak/user/UserService.java
- src/main/java/com/ll/jigumiyak/user/UserSignupForm.java
- src/main/java/com/ll/jigumiyak/util/RsData.java
- src/main/resources/static/login.js
- src/main/resources/static/signup.css
- src/main/resources/static/signup.js
- src/main/resources/templates/login.html
- src/main/resources/templates/signup.html
**RQ-0044**
- 영문+숫자 20자 미만의 아이디를 입력하고 중복확인 버튼을 클릭하면 아이디 중복확인 후 결과를 하단에 표시한다.
**RQ-0046**
- 비밀번호 확인란에 비밀번호를 입력하고 2개의 비밀번호 일치 여부를 하단에 표시한다.
**RQ-0047**
- 이메일 형식의 이메일을 입력하고 중복 여부를 하단에 표시한다. => 하단에 제거
**RQ-0048**
- 인증번호 발송 버튼을 클릭하면 해당 이메일로 인증번호를 발송한다.
**RQ-0049**
- 인증번호를 입력하고 확인 버튼을 클릭하면 성공여부 알림이 생성된다.
**RQ-0052**
- 모든 입력란이 작성되고, 중복되지 않은 아이디, 비밀번호와 비밀번호 확인 일치, 인증된 이메일, 주소 입력 조건이 모두 충족되면 회원가입 버튼이 활성화된다.
- 기존 String 리턴 및 Exception 발생시키는 방식을 ResponseEntity 를 리턴하고 body 에 RsData 를 담는 방식으로 변경
- 예시 코드
`return ResponseEntity.status(HttpStatus.OK)
.body(new RsData<>("S-1", "이메일 인증번호 발송이 완료되었습니다", codeBits[1]));`
- 기존에 100% 로 되어있지만 미비된 부분들 전부 보완 완료
- 현재 코드 상 Binding Error 발생 가능성이 존재할 경우 회원가입 버튼이 비활성화 된 상태
- 차후 백엔드에서 Binding Error 우선 순위 적용해서 리턴하는 코드 및 프런트에서 에러 발생 필드에 에러 메시지 넣어주는 코드 추가 예정
확인 후 리뷰 부탁합니다. …
> 회원가입 - RQ-0044, 0046, 0047, 0048, 0049, 0052

- src/main/resources/static/test.css
- src/main/resources/templates/layout.html
- src/main/resources/templates/navbar.html
- src/main/resources/templates/sidebar.html
- 사이드바
- CL-03
- RQ-0012 : 모든 페이지 우측에서 사이드 바가 표시되고 기능을 이용할 수 있다.	
- RQ-0013 : 페이지 스크롤 위치와 관계없이 사이드 바의 위치는 고정된다.	
- RQ-0014 : 최근 조회한 상품 목록, 찜한 목록 버튼, 장바구니 버튼, 최상단 이동 버튼으로 구성된다.	
- RQ-0018 : 로그인하지 않은 사용자가 찜한 목록 버튼, 장바구니 버튼 클릭 시 [로그인이 필요한 서비스] 에 정의된 대로 진행한다.		
- RQ-0019 : 최상단 이동 버튼 클릭 시 페이지 최상단으로 스크롤이 이동한다.	
- rq-0012 모든 페이지 --> 상품페이지 변경
- 위치 수정 필요
> Feature cl 03

- src/main/java/com/ll/jigumiyak/security/CustomSecurityService.java
- src/main/java/com/ll/jigumiyak/security/SuccessHandler.java
- 로그인
- 06
- 0031
- 소셜 계정 연결 이후 진행되는 loadUser 로직 수정
- 연결된 소셜 계정과 같은 이메일을 보유한 계정 존재 시 해당 계정에 소셜 계정 연결
- 이외의 경우 계정 신규 생성 후 소셜 계정 연결
- 로그인 아이디 == provider_DBid
- 필요 시 같은 계정에 소셜 계정 연결 가능하도록 마이페이지에 기능 추가 예정
> 로그인 - RQ-0031

- src/main/java/com/ll/jigumiyak/security/SuccessHandler.java
- src/main/java/com/ll/jigumiyak/user/SiteUser.java
- src/main/java/com/ll/jigumiyak/user/UserService.java
- 로그인
- 32
- 0223
- 기존에 임시 유저 권한 부여하던 방식에서 임시비밀번호 여부를 체크하는 isTemp 변수를 컬럼으로 추가하는 방식으로 변경
- 회원정보 수정에서 비밀번호 변경 시 임시비밀번호 여부 변경되도록 작업할 예정
> 로그인 - RQ-0223

- src/main/resources/templates/admin/admin_board.html
- src/main/resources/templates/admin/admin_board_comment.html
- src/main/resources/templates/admin/admin_board_recomment.html
- 게시글 관리
- CL-27
-
- 템플릿 경로 수정
-
> 버그 수정 Feature cl 27

- src/main/java/com/ll/jigumiyak/api_and_data_load/ApiCaller.java
- src/main/java/com/ll/jigumiyak/file/FileService.java
- src/main/java/com/ll/jigumiyak/nutrient/NutrientRepository.java
- src/main/java/com/ll/jigumiyak/nutrient/NutrientService.java
- src/main/java/com/ll/jigumiyak/product/Product.java
- src/main/java/com/ll/jigumiyak/product/ProductController.java
- src/main/java/com/ll/jigumiyak/product/ProductForm.java
- src/main/java/com/ll/jigumiyak/product/ProductRepository.java
- src/main/java/com/ll/jigumiyak/product/ProductService.java
- src/main/resources/templates/product_detail.html
- src/main/resources/templates/product_form.html
- src/main/resources/templates/product_list.html
- 상품(등록)
- CL-18
- none(상품등록 / 자동완성으로 영양성분 select)
- input hidden 상자를 만들어서 선택시마다 data value에 추가해서 input태그 복사
- ajax로 자동완성 추가
- 장바구니 or 설문?
> Feature cl 18

- src/main/java/com/ll/jigumiyak/cart/Cart.java
- src/main/java/com/ll/jigumiyak/cart/CartController.java
- src/main/java/com/ll/jigumiyak/cart/CartRepository.java
- src/main/java/com/ll/jigumiyak/cart/CartService.java
- src/main/java/com/ll/jigumiyak/cart_item/CartItem.java
- src/main/java/com/ll/jigumiyak/cart_item/CartItemForm.java
- src/main/java/com/ll/jigumiyak/cart_item/CartItemRepository.java
- src/main/java/com/ll/jigumiyak/cart_item/CartItemService.java
- src/main/java/com/ll/jigumiyak/notice/NoticeController.java
- src/main/java/com/ll/jigumiyak/product/ProductController.java
- src/main/java/com/ll/jigumiyak/product/ProductService.java
- src/main/resources/templates/cart.html
- src/main/resources/templates/product_detail.html
- 상품 상세 + 카트
- CL-19
- CL-20
- ""
- 검증이랑 처리 좀 더 작업이 더 필요할 것 같아요
- 장바구니 접속 /cart (현재 principal로 장바구니 찾음 / 상품을 담지 않으면 카트가 없음)
- 상품 디테일 페이지에서 수량클릭하고 장바구니 누르면 장바구니 생성 및 카트에 복제된 아이템 담김)
- 성공시 메인화면 리턴
- 주문 하고 계시면 나머지 부분 수정하려합니다.
- 이렇게만 전달해도 문제는 크게 없을 것 같긴한데 문제생기면 바로 수정 좀 하죠..
> Feature cl 19

- src/main/java/com/ll/jigumiyak/cart/CartController.java
- src/main/resources/static/js/product.js
- src/main/resources/templates/product_detail.html
- 장바구니
- CL-20
- bug-fix
- bug-fix
-
> cart bug fix

- src/main/java/com/ll/jigumiyak/board/BoardController.java
- src/main/java/com/ll/jigumiyak/inquiry/InquiryController.java
- src/main/java/com/ll/jigumiyak/inquiry/InquiryForm.java
- src/main/java/com/ll/jigumiyak/inquiry/InquiryService.java
- src/main/java/com/ll/jigumiyak/inquiry_answer/InquiryAnswer.java
- src/main/java/com/ll/jigumiyak/inquiry_answer/InquiryAnswerController.java
- src/main/java/com/ll/jigumiyak/inquiry_answer/InquiryAnswerForm.java
- src/main/java/com/ll/jigumiyak/inquiry_answer/InquiryAnswerRepository.java
- src/main/java/com/ll/jigumiyak/inquiry_answer/InquiryAnswerService.java
- src/main/resources/static/test.css
- src/main/resources/templates/inquiry/inquiry_form.html
- src/main/resources/templates/inquiry/inquiry_main.html
- src/main/resources/templates/inquiry/inquiry_success.html
- 문의등록
- CL-14
- RQ-0078 1:1  문의 버튼을 선택하면 문의 제출 화면으로 이동한다.						
- RQ-0079 상단에 문의하기 설명박스가 표시된다.						
- RQ-0080 문의 유형 선택, 제목, 문의내용을 입력할 수 있다.						
- RQ-0082 답변 완료시 이메일로 알림 받기를 신청할 수 있다.						
- RQ-0083 드롭다운으로 문의 유형을 선택할 수 있다.						
- RQ-0084 문의 유형을 선택하고 제목,내용을 입력하면 등록버튼이 활성화된다.						
- RQ-0085 페이지 하단의 취소 버튼 클릭 시 “1:1 문의 작성을 취소하시겠습니까?” 라는 알림 팝업이 생성되고 확인 버튼을 누르면 문의하기 페이지로 이동한다.						
- RQ-0086 문의글을 등록하면 1:1 문의 성공 메세지와 채팅 상담, 상담내역으로 이동하는 버튼이 표시된다.				
- 이미지 첨부 빼고 완료
- 문의 내역
> 문의하기 Feature cl 14

- src/main/java/com/ll/jigumiyak/inquiry/Inquiry.java
- src/main/java/com/ll/jigumiyak/inquiry/InquiryController.java
- src/main/java/com/ll/jigumiyak/inquiry/InquiryForm.java
- src/main/java/com/ll/jigumiyak/inquiry/InquiryRepository.java
- src/main/java/com/ll/jigumiyak/inquiry/InquiryService.java
- src/main/resources/static/test.css
- src/main/resources/templates/board_detail.html
- src/main/resources/templates/faq/faq.html
- src/main/resources/templates/inquiry/inquiry_detail.html
- src/main/resources/templates/inquiry/inquiry_success.html
- src/main/resources/templates/inquiry/list.html
- 문의내역
- cl-15
- RQ-0087 로그인한 사용자가 본인이 등록한 문의내역을 조회할 수 있다.						
- RQ-0090 문의내역 개수가 표시된다.			
- RQ-0091 사용자의 문의내역이 없을 경우 내역없음 아이콘과 함께 1:1 문의 이용을 권장하는 메시지가 표시된다.			
- RQ-0092 페이지 하단의 상담하기 버튼 클릭 시 1:1 문의 폼 페이지로 이동한다.		
- RQ-0093 관리자가 해당 문의에 답변을 작성하면 문의내역 제목 우측에 “[답변완료]” 라고 표시한다.						
- 기간별 조회 아직 안함. 
- 문의 관리
> 문의내역 Feature cl 15

- src/main/java/com/ll/jigumiyak/cart/CartController.java
- src/main/java/com/ll/jigumiyak/cart/CartService.java
- src/main/java/com/ll/jigumiyak/cart_item/CartItem.java
- src/main/java/com/ll/jigumiyak/cart_item/CartItemController.java
- src/main/java/com/ll/jigumiyak/cart_item/CartItemRepository.java
- src/main/java/com/ll/jigumiyak/cart_item/CartItemService.java
- src/main/java/com/ll/jigumiyak/purchase/PurchaseController.java
- src/main/resources/application-prod.properties.default
- src/main/resources/static/js/cart.js
- src/main/resources/templates/cart.html
- src/main/resources/templates/purchase/purchase.html
- 장바구니
- 19, 20
- 0133
- 0134
- 0144
- 0145
- 0146
- 0147
- 0148
- 0149
- 0151
- 0152
- 장바구니 rq 80% 수준 완성
- 수량 변경, 선택 삭제, 선택 주문(전체, 선택 모두 가능), 바로 주문 등 기능 구현
- 장바구니 잔여 작업 마무리
- 주문 페이지 잔여 작업 마무리
- 주문 객체 생성 및 포스트 과정 처리
> 장바구니 - RQ-0133, 0134, 0144, 0145, 0146, 0147, 0148, 0149, 0151, 0152

- src/main/resources/static/js/cart.js
- src/main/resources/templates/cart.html
- 장바구니
- 20
- 0151
- 바로 구매 버튼 클릭 시 전체 form 이 submit 되는 현상 수정
> 장바구니 - RQ-0151 fix

- src/main/java/com/ll/jigumiyak/admin/AdminController.java
- src/main/java/com/ll/jigumiyak/inquiry/InquiryController.java
- src/main/java/com/ll/jigumiyak/user/UserRepository.java
- src/main/java/com/ll/jigumiyak/user/UserService.java
- src/main/java/com/ll/jigumiyak/util/CommonUtil.java
- src/main/resources/templates/admin/inquiry_detail.html
- src/main/resources/templates/board_detail.html
- src/main/resources/templates/footer.html
- src/main/resources/templates/navbar.html
- 문의하기 관리
- cl-34
- RQ-0231 이메일 발송 신청한 작성자에게 확인 이메일을 발송할 수 있다.						
- 로그인 아이디 다를 때 메인화면으로 가게 하긴 했음. 테스트 필요
- 이미지 첨부/ 메인 프론트
> 문의하기 관리 Feature cl 34

- src/main/java/com/ll/jigumiyak/MainController.java
- src/main/resources/templates/index.html
- src/main/resources/templates/navbar.html
- 메인페이지
-
-
- 이상 없으면 메인페이지 이걸로 확정
- 문의 기간 검색, 채팅
> 메인페이지 Feature fr

- src/main/java/com/ll/jigumiyak/address/AddressService.java
- src/main/java/com/ll/jigumiyak/cart_item/CartItemController.java
- src/main/java/com/ll/jigumiyak/cart_item/CartItemService.java
- src/main/java/com/ll/jigumiyak/purchase/Purchase.java
- src/main/java/com/ll/jigumiyak/purchase/PurchaseController.java
- src/main/java/com/ll/jigumiyak/purchase/PurchaseRepository.java
- src/main/java/com/ll/jigumiyak/purchase/PurchaseService.java
- src/main/java/com/ll/jigumiyak/purchase_detail/PurchaseDetailRepository.java
- src/main/java/com/ll/jigumiyak/purchase_item/PurchaseItem.java
- src/main/java/com/ll/jigumiyak/purchase_item/PurchaseItemRepository.java
- src/main/java/com/ll/jigumiyak/purchase_item/PurchaseItemService.java
- src/main/java/com/ll/jigumiyak/security/SuccessHandler.java
- src/main/resources/static/js/purchase.js
- src/main/resources/templates/cart.html
- src/main/resources/templates/purchase/fail.html
- src/main/resources/templates/purchase/purchase.html
- src/main/resources/templates/purchase/success.html
- 결제
- 21
- 0162
- 0164
- 주문 내역 확인 및 결제 버튼 작업 완료
- 결제 버튼 클릭 시 토스페이먼츠 결제 창 활성화
- 토스페이먼츠 결제 완료 시 주문 객체 세부 정보 저장 완료
- 프런트 작업 (약관 동의 및 필수 입력란 검증, 주문 결과 페이지)
- 관리자 작업 먼저 하고 난 후 진행할 예정
> 결제 - RQ-0162, 0164

- src/main/java/com/ll/jigumiyak/admin/AdminController.java
- src/main/java/com/ll/jigumiyak/security/CustomRole.java
- src/main/java/com/ll/jigumiyak/security/CustomSecurityService.java
- src/main/java/com/ll/jigumiyak/user/UserService.java
- src/main/resources/templates/admin/ad_navbar.html
- src/main/resources/templates/admin/admin_user.html
- 관리자 페이지
- 26
- 0194
- 회원 리스트업 작업 우선 진행
- 회원 권한 변경 기능과 관련해서 필요한 권한 추가 및 조정 (총관리자, 탈퇴회원)
- 잔여 작업 수행 예정
- 댓글 수, 리뷰 수 관련 rq 의견 좀 부탁합니다
> 회원관리 - RQ-0194

- src/main/java/com/ll/jigumiyak/security/CustomRole.java
- src/main/java/com/ll/jigumiyak/user/UserController.java
- src/main/java/com/ll/jigumiyak/user/UserService.java
- src/main/resources/static/css/admin_user.css
- src/main/resources/static/js/admin_user.js
- src/main/resources/templates/admin/admin_user.html
- 관리자 페이지
- 26
- 0195
- 0196
- 회원 권한 수정, 탈퇴, 블랙 처리 작업 완료
- 총관리자, 관리자에 따라 처리 가능한 회원 범위 다르게 설정
- 주문, 정산 관련 관리자 페이지 작업 진행
> 회원관리 - RQ-0195, 0196

- build.gradle
- src/main/java/com/ll/jigumiyak/inquiry/InquiryController.java
- src/main/java/com/ll/jigumiyak/inquiry/InquiryService.java
- src/main/java/com/ll/jigumiyak/util/CommonUtil.java
- src/main/resources/templates/admin/inquiry_detail.html
- src/main/resources/templates/board_detail.html
- src/main/resources/templates/chat.html
- src/main/resources/templates/faq/faq.html
- src/main/resources/templates/inquiry/inquiry_detail.html
- src/main/resources/templates/inquiry/list.html
- src/main/resources/templates/notice_detail.html
- 마크다운
-
-
- 마크다운 일부 적용
- 문의하기 사진 수정
-
> 마크다운 Feature markdown

- src/main/java/com/ll/jigumiyak/user/UserController.java
- src/main/resources/templates/mypage.html
- 마이페이지 문의내역
- 36
- 
- 문의내역 미답변만 출력
- 공지사항 관리자
> 마이페이지 Feature cl 36

- src/main/java/com/ll/jigumiyak/admin/AdminController.java
- src/main/java/com/ll/jigumiyak/notice/NoticeRepository.java
- src/main/java/com/ll/jigumiyak/notice/NoticeService.java
- src/main/java/com/ll/jigumiyak/notice_comment/NoticeCommentRepository.java
- src/main/java/com/ll/jigumiyak/notice_comment/NoticeCommentService.java
- src/main/resources/templates/admin/ad_navbar.html
- src/main/resources/templates/admin/notice.html
- src/main/resources/templates/admin/notice_comment.html
- src/main/resources/templates/mypage.html
- src/main/resources/templates/notice_list.html
- src/main/resources/templates/sidebar.html
- 공지사항 관리
- 33
- rq-0224
- rq-0225
- rq-0226
- 공지사항 관리 완성 및 공지사항 페이지 프론트 약간 수정
-
> 공지사항 관리 Feature cl 33

- src/main/java/com/ll/jigumiyak/admin/AdminController.java
- src/main/java/com/ll/jigumiyak/purchase/PurchaseController.java
- src/main/java/com/ll/jigumiyak/purchase/PurchaseService.java
- src/main/java/com/ll/jigumiyak/user/UserController.java
- src/main/resources/static/js/admin_purchase.js
- src/main/resources/templates/admin/ad_navbar.html
- src/main/resources/templates/admin/admin_purchase.html
- 관리자 페이지
- 30
- 0209
- 0210
- 0212
- AdminController에 hasAuthority('admin') annotation 옮김 (추후 컨트롤러 내 메서드에 동일 애너테이션 달지 않아도 됨)
- 구매 결과 목록 나오게 작업 완료
- 상품명 클릭 시 해당 주문의 상세 정보 출력
- 마이페이지 주문내역 작업, 기타 주문 상세 페이지 작업
- 마이페이지 구매확정 기능 추가 및 정산 데이터 반영 작업
> 결제 및 배송 - RQ-0209, 0210, 0212

- src/main/resources/static/js/cart.js
- src/main/resources/templates/cart.html
- 장바구니
- 20
- 0149
- 선택 삭제 기능 버그 픽스
- 장바구니 비어있음 메시지 hidden 기준 수정
> 장바구니 - RQ-0149 fix
